version: '3'
services:
  l1:
    build:
      context: ./l1
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8545 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  coordinator:
    depends_on:
      l1:
        condition: service_healthy
    environment:
      - OP_COMPONENT_TYPE=coordinator
      - ETH_RPC_URL=http://l1:8545 # TODO: will need updating when networking changes`
      # Private key of Admin account for l1 contract deployment, see l2/README.md
      - PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
      - DEPLOYMENT_CONTEXT=primev-settlement
    build:
      context: ./l2
      dockerfile: Dockerfile
  l2-geth:
    depends_on:
      - coordinator
    environment:
      - OP_COMPONENT_TYPE=geth
    build:
      context: ./l2
      dockerfile: Dockerfile
  l2-node:
    depends_on:
      - coordinator
    environment:
      - OP_COMPONENT_TYPE=node
    build:
      context: ./l2
      dockerfile: Dockerfile
  l2-batcher:
    depends_on:
      - coordinator
    environment:
      - OP_COMPONENT_TYPE=batcher
    build:
      context: ./l2
      dockerfile: Dockerfile
  l2-proposer:
    depends_on:
      - coordinator
    environment:
      - OP_COMPONENT_TYPE=proposer
    build:
      context: ./l2
      dockerfile: Dockerfile
  # TODOs include ports exposing