version: '3'
services:
  coordinator:
    build: 
      context: ./coordinator
    volumes:
      - shared-optimism:/shared-optimism
  l1-geth:
    build: 
      context: ./l1-geth
    volumes:
      - shared-optimism:/shared-optimism
  op-geth:
    build: 
      context: ./op-geth
    volumes:
      - shared-optimism:/shared-optimism
  op-node:
    build:
      context: ./op-node
    volumes:
      - shared-optimism:/shared-optimism
  op-batcher:
    build:
      context: ./op-batcher
  op-proposer:
    build:
      context: ./op-proposer
    volumes:
      - shared-optimism:/shared-optimism

volumes:
  shared-optimism:
