version: '3'
services:
  l1:
    build:
      context: ./l1
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/setup_complete && curl -f http://localhost:8545"]
      interval: 10s
      timeout: 10s
      retries: 30
    environment:
      - DEPLOYMENT_CONTEXT=primev-settlement
      # Arbitrary salt for L1 contract deployment, see https://docs.openzeppelin.com/cli/2.8/deploying-with-create2#create2
      # and https://github.com/ethereum-optimism/optimism/issues/7749.
      - IMPL_SALT=primev-settlement
      - GETH_URL=http://localhost:8545
    volumes:
      - shared-optimism:/shared-optimism
  coordinator:
    depends_on:
      l1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/setup_complete"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - OP_COMPONENT_TYPE=coordinator
      - ETH_RPC_URL=http://l1:8545 
    build:
      context: ./l2
      dockerfile: Dockerfile
    volumes:
      - shared-optimism:/shared-optimism
      - shared-l2-config:/shared-l2-config
  l2-geth:
    depends_on:
      coordinator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", "http://l2-geth:8545"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - OP_COMPONENT_TYPE=geth
      - L2_CHAIN_ID=901
    build:
      context: ./l2
      dockerfile: Dockerfile
    volumes:
      - shared-l2-config:/shared-l2-config
  l2-node:
    depends_on:
      l2-geth:
        condition: service_healthy
    environment:
      - OP_COMPONENT_TYPE=node
      - ETH_RPC_URL=http://l1:8545 
      # Private key of Sequencer account for operating op-node, 0x prefix stripped. 
      - SEQ_KEY=47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
    build:
      context: ./l2
      dockerfile: Dockerfile
    volumes:
      - shared-optimism:/shared-optimism
      - shared-l2-config:/shared-l2-config
  l2-batcher:
    depends_on:
      coordinator:
        condition: service_healthy
    environment:
      - OP_COMPONENT_TYPE=batcher
    build:
      context: ./l2
      dockerfile: Dockerfile
  l2-proposer:
    depends_on:
      coordinator:
        condition: service_healthy
    environment:
      - OP_COMPONENT_TYPE=proposer
    build:
      context: ./l2
      dockerfile: Dockerfile
  # TODOs include ports exposing
volumes:
  shared-optimism:
  shared-l2-config:
