version: '3'
services:
  coordinator:
    build: 
      context: .
      dockerfile: Dockerfile-coordinator
    volumes:
      - shared-optimism:/shared-optimism
  l1:
    build: 
      context: .
      dockerfile: Dockerfile-l1
    volumes:
      - shared-optimism:/shared-optimism

volumes:
  shared-optimism:
