version: '3'
services:
  coordinator:
    build: 
      context: ./coordinator
    volumes:
      - shared-optimism:/shared-optimism
    environment:
      - DEPLOYMENT_CONTEXT=${DEPLOYMENT_CONTEXT}
      - L1_BLOCK_TIME=${L1_BLOCK_TIME}
      - L2_BLOCK_TIME=${L2_BLOCK_TIME}
      - GOVERNANCE_TOKEN_SYMBOL=${GOVERNANCE_TOKEN_SYMBOL}
      - GOVERNANCE_TOKEN_NAME=${GOVERNANCE_TOKEN_NAME}
  l1-geth:
    build: 
      context: ./l1-geth
    volumes:
      - shared-optimism:/shared-optimism
  op-geth:
    build: 
      context: ./op-geth
    volumes:
      - shared-optimism:/shared-optimism
  op-node:
    build:
      context: ./op-node
    volumes:
      - shared-optimism:/shared-optimism
  op-batcher:
    build:
      context: ./op-batcher
  op-proposer:
    build:
      context: ./op-proposer
    volumes:
      - shared-optimism:/shared-optimism

volumes:
  shared-optimism:
