FROM us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:optimism

# TODO: double check version of image

RUN apk add --no-cache jq

COPY entrypoint-l2.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
