version: '3'
services:
  coordinator:
    build: 
      context: ./coordinator
    volumes:
      - shared-optimism:/shared-optimism
  l1-geth:
    build: 
      context: ./l1-geth
    volumes:
      - shared-optimism:/shared-optimism
      # TODO: could add /db as persisted volume
  op-geth:
    build: 
      context: ./op-geth
    volumes:
      - shared-optimism:/shared-optimism
      # TODO: could add /db as persisted volume
  op-node:
    build:
      context: ./op-node
    volumes:
      - shared-optimism:/shared-optimism
  op-batcher:
    build:
      context: ./op-batcher

volumes:
  shared-optimism:
